### PR TITLE
feat: fuzzy find files + notes

### PR DESCRIPTION
**Pull request by tami5**
Changes:
- Make ido_find_files only find files.
- Rename ido_find_files to ido_browser as in directory browser.
- Added some notes and thoughts 

Well done on solving the last issue of refreshing ido popup each time we enter a directory.

Feel free to comment on changes and when you merge make sure you do squash and merge so that unnecessary commits here (like Merge branch) doesn't get reflected in the ido.nvim git history.

### CODE REVIEW

**Comment by shoumodip** [comment]
I tested the file search function and it is *slow* (not the `fd` part, the `ido` part). Ido never was meant to replace something like `fzf`. It is meant for quick and simple temporary narrowing functions which can be done from the command mode with as little function writing as possible. For stuff like this which work on a *lot* of items, don't be a hipster. Just use FZF :)

**Comment by tami5** [comment]
:+1:

**Comment by tami5** [comment]
>  Ido never was meant to replace something like fzf

Its sad to see such a waste of possibilities, and no I'm not hipster nor am I ignorant to know that fzf can be used to match files over shell instance in nvim, or that a fzy algorithm ported in lua can be ported. 

next time try to be little nicer to people trying to use and help mature something you've started.

**Comment by shoumodip** [comment]
Jeez, I was just joking. Thought the hipster meme would be appropriate here. Nevertheless, sorry if I unknowingly offended you.

**Comment by tami5** [comment]
No problem sorry for taking it personally 👌

**Pull request closed without merging**
